### ISSUE TITLE
安卓组件引用没有问题，但只要一开始加载地图就cash

### ISSUE THREAD

**Issue by BrutHellman** [qiuxiang/react-native-amap3d#14]
react-native 0.44.3
platform: android
npm: 0.2.1

模拟器: Android 7.0   Nexus_5X_API_24
以下为android studio 的 monitor返回的error信息
`07-19 15:59:30.775 5944-5985/com.hydcarrier E/AndroidRuntime: FATAL EXCEPTION: GLThread 308
                                                              Process: com.hydcarrier, PID: 5944
                                                              java.lang.RuntimeException: createContext failed: EGL_SUCCESS
                                                                  at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1205)
                                                                  at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1196)
                                                                  at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1046)
                                                                  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1416)
                                                                  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)`

测试项目为刚刚init的0.44.3，无其他组件影响

尝试过如下操作：
1. 删除./node_modules重新install
2. 删除./android/build目录
3. 删除./android/app/build目录

**Comment by qiuxiang** [comment]
GLSurfaceView 的问题么。。估计是 SDK 在某些设备上存在 Bug，你有换设备测试吗？

**Comment by BrutHellman** [comment]
手边暂时没有其他设备。。。只不过这半年一直用这个模拟器进行安卓开发，之前也用过另外一位大大的高德地图组件(react-native-smart-amap)也没出问题，开始以为是包冲突，这次是重新开了个一个项目测试出一样的问题

**Comment by BrutHellman** [comment]
不好意思，感谢语应写在前头：忘记感谢 @qiuxiang 大大的分享

**Comment by qiuxiang** [comment]
react-native-smart-amap 是用 2D SDK，当然不会出现 GLSurfaceView 的错误。

用的是模拟器，就比较好解释了，很可能是因为模拟器没有提供 opengl 的接口，或者不兼容，又或者存在 Bug。

还好，3D SDK 除了默认的 GLSurfaceView 渲染还提供基于 TextureView 的 TextureMapView，如果你一定要在模拟器上运行，可以尝试修改 https://github.com/qiuxiang/react-native-amap3d/blob/master/android/src/main/java/cn/qiuxiang/react/amap3d/AMapView.kt#L17 ，继承 MapView 改成继承 TextureMapView，应该就能解决你的问题了。

**Comment by BrutHellman** [comment]
原来如此：但是按照您的指点修改继承 TextureMapView后出现调用高德包的问题：

`07-19 16:40:47.005 12135-12173/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 337
                                                   Process: com.hydcarrier, PID: 12135
                                                   java.lang.RuntimeException: createContext failed: 12288
                                                       at com.amap.api.mapcore.util.j$h.a(GLTextureView.java:1110)
                                                       at com.amap.api.mapcore.util.j$h.a(GLTextureView.java:1101)
                                                       at com.amap.api.mapcore.util.j$h.a(GLTextureView.java:941)
                                                       at com.amap.api.mapcore.util.j$i.l(GLTextureView.java:1341)
                                                       at com.amap.api.mapcore.util.j$i.run(GLTextureView.java:1158)`

**Comment by qiuxiang** [comment]
我错了。。即便是 TextureMapView 也是要用 opengl 的接口的。

还是等你用真机测试吧。

**Comment by BrutHellman** [comment]
在真机上使用没有问题

**Comment by siroer** [comment]
我的在A电脑正常 B电脑一样的错误 还没解决

**Comment by qiuxiang** [comment]
@siroer 好像你并没有理解我说的话。

先不管你遇到的是不是这个问题，至少，你要给我错误日志呀。

**Comment by siroer** [comment]
大神 我正在努力：）

**Comment by chengfeng123** [comment]
我模拟器也出现这个问题，拿了部真机测试一下发现正常的

**Comment by POJOa** [comment]
遇到同样的问题，贴出log。可能是opengl的问题。
04-20 05:46:36.027  3117  3142 E EGL_emulation: tid 3142: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
04-20 05:46:36.027  3117  3142 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd6c19840, error=EGL_BAD_MATCH
04-20 05:46:36.030  3117  3162 D         : HostConnection::get() New Host Connection established 0xcfd49280, tid 3162
04-20 05:46:36.047  3117  3162 W System.err: java.lang.IllegalArgumentException
04-20 05:46:36.048  3117  3162 W System.err:    at com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
04-20 05:46:36.048  3117  3162 W System.err:    at com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
04-20 05:46:36.048  3117  3162 W System.err:    at com.amap.api.col.n3.di$b.createContext(GLESUtility.java:165)
04-20 05:46:36.048  3117  3162 W System.err:    at com.amap.api.col.n3.j$h.a(GLTextureView.java:936)
04-20 05:46:36.048  3117  3162 W System.err:    at com.amap.api.col.n3.j$i.l(GLTextureView.java:1341)
04-20 05:46:36.048  3117  3162 W System.err:    at com.amap.api.col.n3.j$i.run(GLTextureView.java:1158)
04-20 05:46:36.048  3117  3162 E AndroidRuntime: FATAL EXCEPTION: GLThread 222
04-20 05:46:36.048  3117  3162 E AndroidRuntime: Process: com.leyline.construction, PID: 3117
04-20 05:46:36.048  3117  3162 E AndroidRuntime: java.lang.RuntimeException: createContext failed: 12288
04-20 05:46:36.048  3117  3162 E AndroidRuntime:        at com.amap.api.col.n3.j$h.a(GLTextureView.java:1110)
04-20 05:46:36.048  3117  3162 E AndroidRuntime:        at com.amap.api.col.n3.j$h.a(GLTextureView.java:1101)
04-20 05:46:36.048  3117  3162 E AndroidRuntime:        at com.amap.api.col.n3.j$h.a(GLTextureView.java:941)
04-20 05:46:36.048  3117  3162 E AndroidRuntime:        at com.amap.api.col.n3.j$i.l(GLTextureView.java:1341)
04-20 05:46:36.048  3117  3162 E AndroidRuntime:        at com.amap.api.col.n3.j$i.run(GLTextureView.java:1158)
04-20 05:46:36.050   539   717 W ActivityManager:   Force finishing activity com.leyline.construction/.MainActivity

**Comment by qiuxiang** [comment]
这个已经反馈了很多了，就是硬件加速的问题，只出现在模拟器。

**Comment by JoinBelieve** [comment]
@chengfeng123 
我也出现了这个问题，大神解决了没？
java.lang.RuntimeException: createContext failed: EGL_SUCCESS
    at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1222)
    at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1213)
    at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1063)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1429)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by zhuscat** [comment]
模拟器中 Graphics acceleration 改为 Software 可以解决这个问题
