### ISSUE TITLE
Error:Execution failed for task ':react-native-amap3d:compileReleaseKotlin'. > Compilation error. See log for more details

### ISSUE THREAD

**Issue by JohnTree** [qiuxiang/react-native-amap3d#166]
Error:(12, 1) Class 'AMap3DPackage' is not abstract and does not implement abstract member public abstract fun createJSModules(): (Mutable)List<Class<out JavaScriptModule!>!>! defined in com.facebook.react.ReactPackage
Error:Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details

作者遇到过这个问题吗 按照你的文档配置 结果发现运行失败

**Comment by zhouyonghui** [comment]
不要用5.7.0的SDK，用5.3.0SDK

**Comment by qiuxiang** [comment]
与 高德 SDK 无关，显然是因为你的 RN 版本低于 0.47

**Comment by qiuxiang** [comment]
早期 RN 的 ReactPackage 有个必须 Override 的方法 createJSModules，0.47 之后移除了。如果你非要用 RN 低版本，参考 https://github.com/qiuxiang/react-native-amap3d/blob/v0.2.0/android/src/main/java/cn/qiuxiang/react/amap3d/AMap3DPackage.kt 自己加上。

**Comment by michael712520** [comment]
我的rn 5.3也出现这个问题

**Comment by qiuxiang** [comment]
@michael712520 能提供错误信息截图？

**Comment by Jam1zhu** [comment]
```java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-amap3d:compileDebugKotlin'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:16)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.processCompilerExitCode(Tasks.kt:453)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:415)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin(Tasks.kt:309)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more
```
@qiuxiang 大佬，还是有这个问题。
```
// package.json
{
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-amap3d": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/runtime": "^7.4.2",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.5.0",
    "eslint": "^5.15.3",
    "jest": "^24.5.0",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
}

```
gradle：4.10.1

**Comment by k1195453766** [comment]
rn版本：0.59.4
amap3d：1.1.0
gradle：3.3.1
报错：Execution failed for task ':react-native-amap3d:compileDebugKotlin'.

**Comment by k1195453766** [comment]
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\AMapUtils.kt: (20, 66): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapMultiPoint.kt: (19, 51): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapMultiPoint.kt: (20, 29): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapMultiPoint.kt: (21, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapMultiPoint.kt: (23, 29): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapMultiPoint.kt: (24, 44): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: F:\SVNProject\wrh\caocaowaimai\node_modules\react-native-amap3d\lib\android\src\main\java\cn\qiuxiang\react\amap3d\maps\AMapView.kt: (174, 53): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?

**Comment by muyiylh** [comment]
这个问题怎么解决，我也遇到了

**Comment by hjtgzh** [comment]
"react-native": "0.58.4"
这个版本可以，但是版本0.59-0.59.4之间的都报这个错。。。同问

**Comment by k1195453766** [comment]
还没找到问题，换用了react-native-maps组件

**Comment by hjtgzh** [comment]
react-native-maps组件也有这个问题，都是版本的问题

**Comment by muyiylh** [comment]
这个错误是 kotlin 语法不对

**Comment by k1195453766** [comment]
是的，我尝试过升级kotlin,但是失败了

**Comment by muyiylh** [comment]
我按照错误提示，修改了源代码，编译能通过

**Comment by hjtgzh** [comment]
能发下截图吗？

**Comment by muyiylh** [comment]
在报错的地方，在对象后面添加？或者！！

**Comment by hjtgzh** [comment]
> 还没找到问题，换用了react-native-maps组件
react-native-maps组件不支持中国地区吧
