### ISSUE TITLE
android闪退

### ISSUE THREAD

**Issue by only4ly** [qiuxiang/react-native-amap3d#175]
logcat error 如下
01-19 15:23:25.525 8303-8380/com.godiyunapp E/AndroidRuntime: FATAL EXCEPTION: GLThread 373
                                                              Process: com.godiyunapp, PID: 8303
                                                              java.lang.RuntimeException: createContext failed: 12288
                                                                  at com.amap.api.col.n3.j$h.a(GLTextureView.java:1110)
                                                                  at com.amap.api.col.n3.j$h.a(GLTextureView.java:1101)
                                                                  at com.amap.api.col.n3.j$h.a(GLTextureView.java:941)
                                                                  at com.amap.api.col.n3.j$i.l(GLTextureView.java:1341)
                                                                  at com.amap.api.col.n3.j$i.run(GLTextureView.java:1158)
![Uploading 1516346818788.jpg…]()

**Comment by only4ly** [comment]
![1516346818788](https://user-images.githubusercontent.com/16274199/35139359-b1614fb6-fd2d-11e7-825e-1c0f7fea922c.jpg)

**Comment by only4ly** [comment]
好的 感谢
