### ISSUE TITLE
页面空白，请问什么问题？？

### ISSUE THREAD

**Issue by chenyinlong** [qiuxiang/react-native-amap3d#386]
`06:04.963 21853-21853/? E/zygote: No implementation found for long com.autonavi.ae.gmap.GLMapEngine.nativeGetCurrentMapState(int, long) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeGetCurrentMapState and Java_com_autonavi_ae_gmap_GLMapEngine_nativeGetCurrentMapState__IJ)
08-03 14:06:04.964 21853-21853/? W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for long com.autonavi.ae.gmap.GLMapEngine.nativeGetCurrentMapState(int, long) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeGetCurrentMapState and Java_com_autonavi_ae_gmap_GLMapEngine_nativeGetCurrentMapState__IJ)
08-03 14:06:04.964 21853-21853/? W/System.err:     at com.autonavi.ae.gmap.GLMapEngine.nativeGetCurrentMapState(Native Method)
08-03 14:06:04.964 21853-21853/? W/System.err:     at com.autonavi.ae.gmap.GLMapEngine.getMapState(GLMapEngine.java:435)
08-03 14:06:04.964 21853-21853/? W/System.err:     at com.amap.api.mapcore.util.a.c(AMapDelegateImp.java:1176)`

请问是不是没有引入.so 文件的原因，请问怎么处理？

**Comment by chenyinlong** [comment]
抱歉，是的，设置宽高后，显示地图了。非常感谢
