### ISSUE TITLE
pod install 的时候出错

### ISSUE THREAD

**Issue by Chechengyi** [qiuxiang/react-native-amap3d#413]
我的RN版本是0.44.3  

请教您有没有遇到过类似问题， 百度，谷歌好几天了。 没有找到答案

下面是 pod install 之后的信息

/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /Volumes/软件盘/shoukeApp/ios in PATH, mode 040777
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.15.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f27414f23c3e1a7b255210172a120997fd49cf8a
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
react_native_path = '../node_modules/react-native'

platform :ios, '8.0'

# The target name is most likely the name of your project.
target 'shoukeApp' do
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Volumes/软件盘/shoukeApp/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:37:in `initialize'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:812:in `fetch_external_source'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:789:in `block (2 levels) in fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:788:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:788:in `block in fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:787:in `fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/analyzer.rb:100:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:250:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:160:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:159:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:122:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FVolumes%2F%E8%BD%AF%E4%BB%B6%E7%9B%98%2FshoukeApp%2Fnode_modules%2Freact-native%2Fthird-party-podspecs%2FDoubleConversion.podspec&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - i can't use  pod install to install dependencies
   https://github.com/CocoaPods/CocoaPods/issues/8096 [open] [0 comments]
   2 days ago

**Comment by qiuxiang** [comment]
你的 RN 版本太低了，不同的版本 Podfile 写法不一样

**Comment by wd** [comment]
第一行不就是错误信息么？
你看看那个文件是不是存在。

Errno::ENOENT - No such file or directory @ rb_sysopen - /Volumes/软件盘/shoukeApp/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec

这个是这行引入的

  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'

一般来说，你应该不需要这几个 pod 的引入。我这 0.52 及以上是不需要做这个事情的。

**Comment by winterwd** [comment]
为什么这个组件iOS的打入方式要用pod形式？

**Comment by Chechengyi** [comment]
多谢各位给我解答， pod install 的问题已经解决了 但是弄好了一天， ios上的地图就一片空白， 我换成了百度地图然后 ios android 都正常工作了。   个人感觉添加第三方库的时候最好是不要 去 react-native link  手动添加麻烦点， 但是遇见稀奇古怪的错误少点。。 至少对于我而言是稀奇古怪的错误。。。。
