### ISSUE TITLE
地图黑屏，看到有报错

### ISSUE THREAD

**Issue by qilovehua** [qiuxiang/react-native-amap3d#578]
RN: 0.61.5   
./gradlew assembleRelease打的正式包，在真机上安卓，启动页后就直接crash。
用真机调试，显示正常；用模拟器调试，地图显示黑屏，android studio报如下错误。
把地图组件移除后，启动页后能正常进入RN页面。
谁能帮忙看看的，非常感谢！

```
D/SoLoader: init start
    adding system library source: /vendor/lib
    adding system library source: /system/lib
    adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.cunjiapp/lib-main flags = 1]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86 flags = 0]
    Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.cunjiapp/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.cunjiapp/lib-main
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
    so store dirty: regenerating
D/ApkSoSource: not allowing consideration of lib/x86/libAMapSDK_MAP_v6_6_0.so: deferring to libdir
    not allowing consideration of lib/x86/libc++_shared.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/x86/libfb.so: deferring to libdir
    not allowing consideration of lib/x86/libfolly_futures.so: deferring to libdir
    not allowing consideration of lib/x86/libfolly_json.so: deferring to libdir
    not allowing consideration of lib/x86/libglog.so: deferring to libdir
    not allowing consideration of lib/x86/libglog_init.so: deferring to libdir
    not allowing consideration of lib/x86/libhermes-executor-debug.so: deferring to libdir
    not allowing consideration of lib/x86/libhermes-executor-release.so: deferring to libdir
    not allowing consideration of lib/x86/libhermes-inspector.so: deferring to libdir
    not allowing consideration of lib/x86/libhermes.so: deferring to libdir
    not allowing consideration of lib/x86/libimagepipeline.so: deferring to libdir
    not allowing consideration of lib/x86/libjscexecutor.so: deferring to libdir
    not allowing consideration of lib/x86/libjsijniprofiler.so: deferring to libdir
    not allowing consideration of lib/x86/libjsinspector.so: deferring to libdir
    not allowing consideration of lib/x86/libnative-filters.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/x86/libnative-imagetranscoder.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/x86/libreactnativeblob.so: deferring to libdir
    not allowing consideration of lib/x86/libreactnativejni.so: deferring to libdir
    not allowing consideration of lib/x86/libyoga.so: deferring to libdir
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
    Finished regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.cunjiapp/lib-main (from syncer thread)
    not releasing dso store lock for /data/user/0/com.cunjiapp/lib-main (syncer thread started)
D/SoLoader: init finish: 4 SO sources prepared
    init exiting
W/System.err: java.lang.ClassNotFoundException: com.facebook.flipper.ReactNativeFlipper
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.cunjiapp.MainApplication.initializeFlipper(MainApplication.java:62)
        at com.cunjiapp.MainApplication.onCreate(MainApplication.java:47)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.flipper.ReactNativeFlipper" on path: DexPathList[[zip file "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86, /data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 15 more
D/SoLoader: About to load: libjscexecutor.so
D/SoLoader: libjscexecutor.so not found on /data/data/com.cunjiapp/lib-main
D/SoLoader: libjscexecutor.so found on /data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86
    Not resolving dependencies for libjscexecutor.so
E/SoLoader: Error when loading lib: dlopen failed: library "libjsc.so" not found lib hash: 3cef2f0752e911a432c024d2f07e1b8d search path is /data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86
    couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found
D/ReactNative: ReactInstanceManager.ctor()
D/SoLoader: init exiting

D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
D/: HostConnection::get() New Host Connection established 0x9226fe80, tid 8508
D/EGL_emulation: eglCreateContext: 0xa192d540: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xa192d540: ver 3 0 (tinfo 0x92ee60b0)
**E/linker: "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86/libAMapSDK_MAP_v6_6_0.so" has invalid e_shstrndx
E/zygote: No implementation found for void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam and Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
E/zygote: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)**
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
        at com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit(Native Method)
        at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:3015)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3011)
        at com.amap.api.mapcore.util.c.createSurface(AMapDelegateImp.java:5661)
        at com.autonavi.ae.gmap.GLMapRender.onSurfaceCreated(GLMapRender.java:235)
        at com.amap.api.mapcore.util.o$i.l(GLTextureView.java:1488)
W/System.err:     at com.amap.api.mapcore.util.o$i.run(GLTextureView.java:1201)
E/linker: "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86/libAMapSDK_MAP_v6_6_0.so" has invalid e_shstrndx
E/zygote: No implementation found for void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam and Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
E/zygote: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
W/System.err:     at com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit(Native Method)
        at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:3015)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3011)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3022)
        at com.amap.api.mapcore.util.c.changeSurface(AMapDelegateImp.java:5652)
        at com.autonavi.ae.gmap.GLMapRender.onSurfaceChanged(GLMapRender.java:226)
        at com.amap.api.mapcore.util.o$i.l(GLTextureView.java:1501)
        at com.amap.api.mapcore.util.o$i.run(GLTextureView.java:1201)
D/EGL_emulation: eglMakeCurrent: 0xa192d540: ver 3 0 (tinfo 0x92ee60b0)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
E/linker: "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86/libAMapSDK_MAP_v6_6_0.so" has invalid e_shstrndx
E/zygote: No implementation found for void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam and Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
I/zygote: NativeAlloc concurrent copying GC freed 21742(1376KB) AllocSpace objects, 9(180KB) LOS objects, 49% free, 4MB/8MB, paused 531us total 108.822ms
E/zygote: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
        at com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit(Native Method)
        at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:3015)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3011)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3022)
        at com.amap.api.mapcore.util.c.changeSurface(AMapDelegateImp.java:5652)
        at com.autonavi.ae.gmap.GLMapRender.onSurfaceChanged(GLMapRender.java:226)
        at com.amap.api.mapcore.util.o$i.l(GLTextureView.java:1501)
W/System.err:     at com.amap.api.mapcore.util.o$i.run(GLTextureView.java:1201)
I/zygote: Do full code cache collection, code=106KB, data=110KB
I/zygote: After code cache collection, code=97KB, data=68KB
D/EGL_emulation: eglMakeCurrent: 0xa192d540: ver 3 0 (tinfo 0x92ee60b0)
E/linker: "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86/libAMapSDK_MAP_v6_6_0.so" has invalid e_shstrndx
E/zygote: No implementation found for void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam and Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
E/zygote: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
        at com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit(Native Method)
        at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:3015)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3011)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3022)
        at com.amap.api.mapcore.util.c.changeSurface(AMapDelegateImp.java:5652)
        at com.autonavi.ae.gmap.GLMapRender.onSurfaceChanged(GLMapRender.java:226)
        at com.amap.api.mapcore.util.o$i.l(GLTextureView.java:1501)
        at com.amap.api.mapcore.util.o$i.run(GLTextureView.java:1201)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
D/EGL_emulation: eglMakeCurrent: 0xa192d540: ver 3 0 (tinfo 0x92ee60b0)
E/linker: "/data/app/com.cunjiapp-3AYXkBBcSfWjuLzv7UxNUw==/lib/x86/libAMapSDK_MAP_v6_6_0.so" has invalid e_shstrndx
E/zygote: No implementation found for void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam and Java_com_autonavi_ae_gmap_GLMapEngine_nativeInitParam__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
E/zygote: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit() (tried Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit and Java_com_autonavi_amap_mapcore_AMapNativeRenderer_nativeDrawLineInit__)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
W/System.err:     at com.autonavi.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit(Native Method)
        at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:3015)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3011)
        at com.amap.api.mapcore.util.c.a(AMapDelegateImp.java:3022)
W/System.err:     at com.amap.api.mapcore.util.c.changeSurface(AMapDelegateImp.java:5652)
        at com.autonavi.ae.gmap.GLMapRender.onSurfaceChanged(GLMapRender.java:226)
W/System.err:     at com.amap.api.mapcore.util.o$i.l(GLTextureView.java:1501)
        at com.amap.api.mapcore.util.o$i.run(GLTextureView.java:1201)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
I/chatty: uid=10080(com.cunjiapp) RenderThread identical 1 line
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
I/ReactNativeJS: ┘ %c action %cUSER_LOCATION %c@ 15:04:49.698 %c(in 209.00 ms)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
D/EGL_emulation: eglMakeCurrent: 0xa33053c0: ver 3 0 (tinfo 0xa3303410)
```

<img width="378" alt="package" src="https://user-images.githubusercontent.com/12076175/74509251-fd539700-4f3b-11ea-8307-86b6eebf92a5.png">

**Comment by qiuxiang** [comment]
这是因为模拟器不支持 3D 加速

**Comment by qilovehua** [comment]
@qiuxiang 真机android9安装了闪退，地图移除就正常

**Comment by qiuxiang** [comment]
真机闪退提供下出错的 logcat

**Comment by qilovehua** [comment]
@qiuxiang 
[logcat.txt](https://github.com/qiuxiang/react-native-amap3d/files/4211536/logcat.txt)

**Comment by qilovehua** [comment]
打包后一个debug，一个release
debug的安装后地图是正常
release闪退

**Comment by qilovehua** [comment]
@qiuxiang 大佬能从logcat看出什么问题吗？谢谢

**Comment by xjy0925** [comment]
MainApplication.java - onCreate方法移除下面这行, 试一下
  // initializeFlipper(this); // Remove this line if you don't want Flipper enabled

**Comment by zim-lee** [comment]
解决了么，我遇到一样的错误，debug正常，真机release闪退
`Throwing new exception 'no non-static method "Lcom/autonavi/base/ae/gmap/GLMapEngine;.reloadMapResource(ILjava/lang/String;I)V"' with unexpected pending exception: java.lang.NoSuchMethodError: no non-static method "Lcom/autonavi/base/ae/gmap/GLMapEngine;.requireMapResource(ILjava/lang/String;)[B"
  at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
  at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1115)
  at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1069)
  at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1007)
  at void java.lang.System.loadLibrary(java.lang.String) (System.java:1667)
  at boolean e.a.a.a.a.ze.a(java.lang.String) (:-1)
  at boolean e.a.a.a.a.ze.a(android.content.Context, e.a.a.a.a.id, e.a.a.a.a.Lf, java.lang.String) (:-1)
  at boolean com.autonavi.base.amap.mapcore.b.b(android.content.Context) (:-1)
  at void e.a.a.a.a.Ra.a(int, javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (:-1)
  at void e.a.a.a.a.Ra.a(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (:-1)
  at void com.autonavi.base.ae.gmap.g.onSurfaceCreated(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (:-1)
  at void e.a.a.a.a.Pg$i.n() (:-1)
  at void e.a.a.a.a.Pg$i.run() (:-1)`

**Comment by zim-lee** [comment]
`enableProguardInReleaseBuilds=false`不报错

**Comment by krmao** [comment]
> `enableProguardInReleaseBuilds=false`不报错

thanks! it works! @zim-lee
