### ISSUE TITLE
安卓真机上使用一段时间后会崩溃

### ISSUE THREAD

**Issue by HADB** [qiuxiang/react-native-amap3d#59]
机器：Vivo X9
情况描述：每次拖动地图会加载附近的Marker，大约几十个，拖动几次之后会闪退，屡试不爽，通过调试模式，报错如下：

```
nodeHandle.getHostNode is not a function

findNumbericNodeHandleStack
ReactNativeStack-dev.js:2324:89

Marker._sendCommand
BaseComponent.js:17:21

<unknown>
Marker.js:138:28

...
```

Android Studio上抓到的Error如下：
```
09-05 21:03:07.210 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: d09141f: Draw requested for a non-attached controller 526ae1d. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.212 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: ff9336c: Draw requested for a non-attached controller 1f32892. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.215 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: c4dfd35: Draw requested for a non-attached controller dd0f263. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.217 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: c5925ca: Draw requested for a non-attached controller 7638e60. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.219 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: fb4d33b: Draw requested for a non-attached controller 9050f19. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.221 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 2fc1a58: Draw requested for a non-attached controller 8173bde. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.224 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: d6e37b1: Draw requested for a non-attached controller 1d651bf. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.226 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: cbd496: Draw requested for a non-attached controller de3308c. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.229 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 3936817: Draw requested for a non-attached controller ace83d5. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.231 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 8448404: Draw requested for a non-attached controller 1d737ea. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.233 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 47d9ded: Draw requested for a non-attached controller 4a84adb. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.235 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 1e8a422: Draw requested for a non-attached controller 2d8c978. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.238 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 65c6eb3: Draw requested for a non-attached controller e808851. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.240 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 87dc70: Draw requested for a non-attached controller 5e8e8b6. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.242 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: da32be9: Draw requested for a non-attached controller dd6b9b7. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.245 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 510e06e: Draw requested for a non-attached controller b8d0524. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.247 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: fa5430f: Draw requested for a non-attached controller 74588d. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.250 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 664f9c: Draw requested for a non-attached controller e92da42. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.252 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 6799da5: Draw requested for a non-attached controller 4133a53. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.254 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 26e957a: Draw requested for a non-attached controller 7274f90. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.257 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: fd012b: Draw requested for a non-attached controller f5af089. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
09-05 21:03:07.259 9625-9625/com.xxx.xxx E/unknown:DraweeEventTracker: 456c988: Draw requested for a non-attached controller 1f8588e. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, trimmed=false, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
```

**Comment by HADB** [comment]
补充：Marker是自定义的图片，另外发现跟Marker数量无关，把Marker数量降低到1，来回多拖几次地图多刷新几次Marker也会出现这个情况

**Comment by qiuxiang** [comment]
先确定下是哪里引发的错误，就现在来看，可能是 js 端，https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/components/BaseComponent.js#L17 就错误日志来看，貌似是 `findNodeHandle` 出错了，试下 try catch，或检查返回值。

另外，造成闪退的 error 也要看下，上面列出的并不是造成闪退的 error，真正造成闪退的 error 是应该包含调用栈的。

**Comment by HADB** [comment]
尝试了很久，发现又是Marker的key的问题，之前的key采用的是
```
key={`${bike.id}-${bike.distance}`}
```
这样的字符串，后来我直接用bike.id就没问题了，很诡异。

**Comment by HADB** [comment]
现在问题是这样：
如果使用bike.id作为key，在安卓上一点问题都没有，但是在ios上，每次加载数据的时候，会有些marker不跟随地图移动（这个问题之前也发过issue和你探讨过），这个安卓和ios上的处理可能不同，安卓就没这个问题；
如果通过`${bike.id}-${bike.distance}`作为key，这样可以保证每次加载回来的key都不同，这样ios上每次加载回来的marker都会跟随地图移动，但是貌似在安卓上，marker的key变化多次会导致崩溃。

我想，这个问题的解决方案可能需要研究下为何返回重复的key会导致ios上那些marker不跟随地图移动。我的理解是，如果动态返回过来的key和之前已经存在的key相同，应该更新这些marker的位置。


具体我近期抽空再试下，帮你找到具体原因。

**Comment by HADB** [comment]
安卓崩溃的error应该是这个：
```
09-06 00:49:31.563 3054-4739/? W/System.err: java.lang.RuntimeException: getUniform: glError 1281
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.di.a(GLESUtility.java:33)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.cw$c.<init>(GLShaderManager.java:196)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.cw.b(GLShaderManager.java:36)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.cw.a(GLShaderManager.java:96)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.a.s(AMapDelegateImp.java:6075)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.p.k(MapOverlayImageView.java:498)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.p.a(MapOverlayImageView.java:515)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.p.a(MapOverlayImageView.java:434)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.p.a(MapOverlayImageView.java:404)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.a.afterDrawLabel(AMapDelegateImp.java:5604)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.autonavi.ae.gmap.GLMapEngine.onMapSurfaceRenderer(GLMapEngine.java:1033)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.autonavi.ae.gmap.GLMapEngine.nativeDrawFrame(Native Method)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.autonavi.ae.gmap.GLMapEngine.drawFrame(GLMapEngine.java:318)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.a.drawFrame(AMapDelegateImp.java:2231)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.autonavi.ae.gmap.GLMapRender.drawSingleFrame(GLMapRender.java:166)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.autonavi.ae.gmap.GLMapRender.onDrawFrame(GLMapRender.java:181)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.j$i.l(GLTextureView.java:1469)
09-06 00:49:31.563 3054-4739/? W/System.err:     at com.amap.api.col.n3.j$i.run(GLTextureView.java:1158)
09-06 00:49:31.858 3054-3054/? W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTEventEmitter.receiveEvent([39,"onLocation",{"accuracy":20,"longitude":121.40664957682291,"latitude":31.209455837673612}])
09-06 00:49:33.869 3054-3054/? W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTEventEmitter.receiveEvent([39,"onLocation",{"accuracy":20,"longitude":121.411298828125,"latitude":31.207610405815974}])
09-06 00:49:34.957 3054-3054/? E/unknown:DraweeEventTracker: ed71b5e: Draw requested for a non-attached controller 
```

**Comment by qiuxiang** [comment]
看起来不是

**Comment by qiuxiang** [comment]
就这里来说，用 `bike.id` 是合理的，我再去看下，ios 相同 key 的时候为什么会有问题。

**Comment by qiuxiang** [comment]
对了，你只是自定义图片，建议用 [`image`](https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/components/maps/Marker.js#L58)，[参考最新的 example](https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/example/src/examples/marker.js#L69)

**Comment by qiuxiang** [comment]
另外，我试了之前用 index 作为 key 的代码，没有再出现 bug，这和直观上的认识是一致的，如果 key 相同，属性不同，则只是调用原生方法去更新属性。

**Comment by qiuxiang** [comment]
我现在倒是比较关注 android 崩溃的 bug，最好能给我具体重现的方式和代码。

**Comment by HADB** [comment]
目前我改成`image`的方式，是很完美的

用`icon`在安卓上崩溃的重现的方式就是动态加载marker，每次滑动地图，在onStatusChangeCompleteHandler里都更新一次，用不同的key（我之前是用的主键id+距离），另外在onLocationHandler里去更新一个其他的state，多拖几次地图就会崩溃。

ios上的话，用`icon`时，如果marker只有1个，我发现key重复确实没问题，但是marker多了之后，并且每次返回的顺序不一样的话，更新就会有问题，有些marker不会随着地图的拖动而移动（我是通过marker的主键id作为key的，拖动地图时，是根据距离把最近的一些marker的id和坐标返回回来，这个时候会出现更新的marker的顺序和之前不一样的情况，例如之前是`1001,1002,1003`这三个marker，下一次获取的数据可能是`1003,1001,1002`这样的顺序，这个时候在ios上marker的更新就会有问题，就会有一部分跟着地图动，有一部分不跟着地图动）

问题代码如下（未做删减，只改掉了敏感信息）：

```javascript
import React, { Component } from 'react'
import { AsyncStorage, Button, Image, Platform, StyleSheet, Switch, Text, TouchableHighlight, TouchableOpacity, TouchableWithoutFeedback, View } from 'react-native'
import { MapView, Marker } from 'react-native-amap3d'
import SplashScreen from 'react-native-splash-screen'
import Utils from '../utils'
import HomeMore from '../components/home-more'
import Toast from 'react-native-toast'

export default class HomeScreen extends Component {
    static navigationOptions = ({ navigation }) => {
        return {
            headerTitle: 'XXX',
            headerBackTitle: '返回',
            headerStyle: {
                backgroundColor: '#282830'
            },
            headerTitleStyle: {
                color: '#fff'
            },
            headerTintColor: '#fff',
            headerBackTitleStyle: {
                color: '#fff'
            },
            headerRight: (
                <TouchableOpacity
                    onPress={() => {
                        navigation.state.params.toggleHomeMore()
                    }}>
                    <Image
                        style={styles.headerRightButtonImage}
                        source={require('../../res/images/plus.png')} />
                </TouchableOpacity>
            )
        }
    }

    constructor(props) {
        super(props)
        this.state = {
            needMoveToLocation: true,
            hasGetLocation: false,
            homeMoreVisiable: false,
            markers: [],
            center: {
                lng: 116.397428,
                lat: 39.90923
            },
            bikeProblemType: -1,
            searchTab: [{
                list: [
                    { name: '全部', status: -1 },
                    { name: '维护', status: 1 },
                    { name: '失联', status: 2 },
                ]
            }, {
                list: [
                    { name: '低电', status: 3 },
                    { name: '未动', status: 4 },
                    { name: '找到', status: 5 },
                ]
            }],
        }

        this.toggleHomeMore = this.toggleHomeMore.bind(this)
        this.hideHomeMore = this.hideHomeMore.bind(this)
        this.loadBikes = this.loadBikes.bind(this)
    }

    componentWillMount() {
        Utils.auth.check(this.props.navigation)
    }

    componentDidMount() {
        this.props.navigation.setParams({
            toggleHomeMore: this.toggleHomeMore
        });
        setTimeout(() => {
            SplashScreen.hide()
        }, 1000)
    }

    toggleHomeMore() {
        this.setState({ homeMoreVisiable: !this.state.homeMoreVisiable })
    }

    hideHomeMore() {
        this.setState({ homeMoreVisiable: false })
    }

    loadBikes() {
        if (this.state.hasGetLocation) {
            Utils.fetch({
                path: 'XXX',
                method: 'POST',
                data: {
                    center: this.state.center,
                    bikeProblemType: this.state.bikeProblemType
                },
                navigation: this.props.navigation
            }).then((data) => {
                data.results.map((bike) => {
                    if (bike.tags.length === 0) {
                        bike.tags.push('正常')
                    }
                })
                this.setState({ markers: data.results })
            })
        }
    }

    onLocationHandler(nativeEvent) {
        this.setState({
            hasGetLocation: true
        })
        if (this.state.needMoveToLocation) {
            this.mapView.animateTo({
                tilt: 0,
                rotation: 0,
                zoomLevel: 18,
                coordinate: {
                    latitude: nativeEvent.latitude,
                    longitude: nativeEvent.longitude,
                }
            })
        }
        this.state.needMoveToLocation = false
    }

    onStatusChangeCompleteHandler(nativeEvent) {
        this.setState({
            center: {
                lng: nativeEvent.longitude,
                lat: nativeEvent.latitude
            }
        }, () => {
            this.loadBikes()
        })
    }

    onMarkerInfoPress(bikeCode) {
        Utils.navigation.navigate({
            navigation: this.props.navigation,
            routeName: 'BikeOperation',
            params: {
                enterScreen: 'Home',
                bikeCode: bikeCode
            }
        })
    }

    onSearchPress(type) {
        this.hideHomeMore()
        this.setState({
            bikeProblemType: type
        }, () => {
            this.loadBikes()
        })
    }

    renderHomeMore() {
        if (this.state.homeMoreVisiable) {
            return (
                <HomeMore
                    navigation={this.props.navigation}
                    hideHomeMore={this.hideHomeMore}>
                </HomeMore>)
        }
    }

    renderBikeMarker(bike) {
        let imgSource = require('../../res/images/bike-marker-normal.png')
        if (bike.tags.indexOf('维护中') >= 0) {
            imgSource = require('../../res/images/bike-marker-inmaintenance.png')
        } else if (bike.tags.indexOf('失联') >= 0) {
            imgSource = require('../../res/images/bike-marker-lost.png')
        } else if (bike.tags.indexOf('低电量') >= 0) {
            imgSource = require('../../res/images/bike-marker-lowpower.png')
        } else if (bike.tags.indexOf('未动') >= 0) {
            imgSource = require('../../res/images/bike-marker-lowusage.png')
        }
        let view = (
            <View style={styles.marker}>
                <Image style={styles.marker} source={imgSource} />
            </View>
        )
        return view
    }

    render() {
        return (
            <View style={StyleSheet.absoluteFill}>
                {
                    this.renderHomeMore()
                }
                <TouchableHighlight
                    onPress={() => {
                        this.hideHomeMore()
                        this.state.needMoveToLocation = true
                    }}
                    style={styles.getLocationButton}>
                    <Image
                        style={styles.getLocationImage}
                        source={require('../../res/images/get-location.png')}
                    />
                </TouchableHighlight>
                <TouchableWithoutFeedback onPress={() => { this.hideHomeMore() }}>
                    <View style={styles.search}>
                        {
                            this.state.searchTab.map((type, index) => {
                                return (
                                    <View
                                        style={[styles.searchFlex]}
                                        key={`tab-${index}`}>
                                        {
                                            type.list.map((item) => {
                                                return (
                                                    <TouchableOpacity
                                                        key={`tab-${index}-${item.status}`}
                                                        style={[styles.searchItem, this.state.bikeProblemType === item.status && styles.searchItemActive]}
                                                        onPress={() => this.onSearchPress(item.status)}>
                                                        <Text
                                                            style={this.state.bikeProblemType === item.status && styles.searchItemActiveColor}>
                                                            {item.name}
                                                        </Text>
                                                    </TouchableOpacity>
                                                )
                                            })
                                        }
                                    </View>
                                )
                            })
                        }
                    </View>
                </TouchableWithoutFeedback>
                <MapView
                    ref={ref => this.mapView = ref}
                    locationEnabled={true}
                    onLocation={({ nativeEvent }) => {
                        this.onLocationHandler(nativeEvent)
                    }}
                    onStatusChangeComplete={({ nativeEvent }) => {
                        this.onStatusChangeCompleteHandler(nativeEvent)
                    }}
                    onPress={() => { this.hideHomeMore() }}
                    zoomLevel={18}
                    showsIndoorMap={true}
                    showsCompass={false}
                    showsScale={true}
                    showsLocationButton={false}
                    showsZoomControls={false}
                    tilt={0}
                    tiltEnabled={false}
                    style={styles.map} >
                    {
                        this.state.markers.map((bike, i) => {
                            const key = bike.id + '' + parseInt(bike.distance * 100) // 使用这个key在安卓上会崩溃
                            // const key = bike.id // 使用这个key在ios上会有部分marker不跟着地图的移动而移动

                            return (
                                <Marker
                                    key={key}
                                    icon={
                                        () => this.renderBikeMarker(bike)
                                    }
                                    onInfoWindowPress={() => {
                                        this.onMarkerInfoPress(bike.code)
                                    }}
                                    title={`车编号:${bike.code}`}
                                    description={`距离:${bike.distance.toFixed(1)}米, 标签:${bike.tags.join(',')}`}
                                    coordinate={{ latitude: bike.lat, longitude: bike.lng }}>
                                </Marker>
                            )
                        })
                    }
                </MapView>
                <View
                    style={styles.centerPinContainer}
                    pointerEvents="none">
                    <Image
                        style={styles.centerPin}
                        source={require('../../res/images/center-pin.png')}>
                    </Image>
                </View>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    absoluteFill: {
        position: 'relative',
    },
    headerRightButtonImage: {
        width: 18,
        height: 18,
        marginRight: 10,
    },
    getLocationButton: {
        position: 'absolute',
        width: 40,
        height: 40,
        left: 20,
        bottom: 40,
        borderRadius: 20,
        zIndex: 1
    },
    getLocationImage: {
        width: 40,
        height: 40
    },
    map: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
    },
    centerPinContainer: {
        position: 'absolute',
        left: 0,
        top: 90,
        bottom: 0,
        right: 0,
        justifyContent: 'center',
        alignItems: 'center'
    },
    centerPin: {
        width: 44,
        height: 72
    },
    scanButton: {
        color: '#fff'
    },
    marker: {
        width: 40,
        height: 40,
    },
    customInfoWindow: {
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 10,
        elevation: 4,
        borderWidth: 1,
        borderColor: '#689F38',
        width: 200,
        height: 100,
        left: -90,
        bottom: 80
    },
    search: {
        backgroundColor: '#fff',
        opacity: 0.9,
        paddingTop: 10,
        paddingRight: 10,
        borderBottomWidth: 1,
        borderColor: '#eee',
    },
    searchFlex: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    searchItem: {
        flex: 1,
        height: 30,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 6,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    searchItemActive: {
        backgroundColor: '#78C84B',
        borderColor: '#78C84B',
    },
    searchItemActiveColor: {
        color: '#fff',
    },
});

```

目前我已经改用`image`的方式去显示Marker，通过bikeId作为key，安卓和ios上都很完美。
