### ISSUE TITLE
Demo 错误

### ISSUE THREAD

**Issue by zhang-wenchao** [qiuxiang/react-native-amap3d#655]
[Mon Oct 19 2020 15:08:15.258]  BUNDLE  ./index.js 

error: Error: While trying to resolve module `react-native-amap3d` from file `/Users/wenchao/Develop/Discovery/react-native-amap3d/example/examples/map-types.js`, the package `/Users/wenchao/Develop/Discovery/react-native-amap3d/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/wenchao/Develop/Discovery/react-native-amap3d/lib/js`. Indeed, none of these files exist:

  * /Users/wenchao/Develop/Discovery/react-native-amap3d/lib/js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/wenchao/Develop/Discovery/react-native-amap3d/lib/js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/wenchao/Develop/Discovery/react-native-amap3d/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)

**Comment by ninetowns** [comment]
@zhang-wenchao 我也遇到了，你是怎么解决的
