### ISSUE TITLE
android studio真机启动报错

### ISSUE THREAD

**Issue by qianzhangsheng** [qiuxiang/react-native-amap3d#690]
按照官方设置以后
`
E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Native module AMapOffline tried to override AMapOfflineModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:55)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:764)
`

`
"react-native": "0.64.1",
"react-native-amap3d": "2.0.2",
`

**Comment by heyden-suimu** [comment]
我也碰到了相似的问题，
